config/routes.rb
Bookmarks::Application.routes.draw do
	resources :sections do
		resources :links
	end

	root to: 'sections#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url

	validates :title, presence: true
	validates :url, presence: true

	belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :position, :name

	validates :name, presence: true, uniqueness: true
	validates :position, presence: true, uniqueness: true

	has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :lookup_section

	def new
		@link = @section.links.build
	end

	def create
		@section.links.create title: params[:link][:title], url: params[:link][:url]
		redirect_to root_path
	end

	def edit
		@link = @section.links.find(params[:id])
	end

	def update
		@link = @section.links.find(params[:id])
		@link.update_attributes params[:link]
		redirect_to root_path
	end

	def destroy
		@link = @section.links.find(params[:id])
		@link.destroy
		redirect_to root_path
	end

	private

	def lookup_section
		@section = Section.find(params[:section_id])
	end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

	def index
		@sections = Section.all
	end

	def edit
		@section = Section.find(params[:id])
	end

	def new
		@section = Section.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for [ @section, @link ] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :url, 'URL' %>
	<%= f.text_field :url %>
	<br>
	<%= f.submit %>
<% end %>

app/views/links/_link.html.erb
<li>
	<a href="<%= link.url %>" title="<%= link.url %>" rel="external"><%= link.title %></a>
	<%= link_to 'Edit', edit_section_link_path(link.section, link) %>
	<%= link_to 'Delete', section_link_path(link.section, link), method: :delete, confirm: 'Really delete this link?' %>
</li>

app/views/links/edit.html.erb
<%= render 'form' %>

app/views/links/new.html.erb
<%= render 'form' %>

app/views/sections/_form.html.erb
<%= form_for @section do |f| %>
	<label>
		Name:
		<%= f.text_field :name %>
	</label>
	<br>
	<%= f.submit %>
<% end %>

app/views/sections/_section.html.erb
<section data-id="<%= section.id %>">
	<header>
		<%= link_to section.name, edit_section_path(section) %>
		<%= link_to '+', new_section_link_path(section), class: 'add' %>
	</header>
	<ul>
		<%= render section.links %>
	</ul>
</section>

app/views/sections/edit.html.erb
<h1>Edit section "<%= @section.name %>"</h1>
<%= render 'form' %>

app/views/sections/index.html.erb
<%= render @sections %>

<footer>
	<%= link_to 'New section', new_section_path %>
</footer>

app/views/sections/new.html.erb
<h1>New section</h1>
<%= render 'form' %>